name: felt_learning_app
description: A felt-textured educational learning app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
<<<<<<< HEAD
    - assets/images/
=======
    - assets/images/  
>>>>>>> 06642cdc92072c5bee0d96266600f08ab9589c4f
